version: '3'
services:
  app:
    build: .
    env_file: env_file
    volumes:
      - ckan:/usr/lib/ckan
      - ./config:/etc/ckan
      - .:/opt/inventory-app
      - ../ckanext-datajson/:/usr/lib/ckan/src/ckanext-datajson/
      # - /local/path/ckanext-some_extension/:/usr/lib/ckan/src/ckanext-some_extension/
