version: '3'
services:
  ckan:
    environment:
      - CKAN_SITE_URL=http://ckan:5000
    volumes:
      - ./e2e/00-setup-cypress-user.sh:/docker-entrypoint.d/00-setup-cypress-user.sh
      - .:/app/
  test:
    image: cypress/included:7.3.0
    entrypoint: []
    command: /bin/bash -c "npm install cypress-downloadfile chance && npx wait-on http://ckan:5000/api/action/status_show && cypress run"
    # To run specific test, use the following syntax:
    #command: /bin/bash -c "npm install cypress-downloadfile chance && npx wait-on http://ckan:5000/api/action/status_show && cypress run --spec cypress/integration/dcat_us_export.spec.js"
    # To run against a dev or production image, use the following syntax:
    # command: /bin/bash -c "CYPRESS_BASE_URL=https://inventory-dev-datagov.app.cloud.gov/ cypress run"
    environment:
      # Created cypress user and password, setup in 00-setup-cypress-user.sh
      - CYPRESS_USER=cypress-user
      - CYPRESS_USER_PASSWORD=cypress-user-password
      - CYPRESS_CKAN_URL=http://ckan:5000
    working_dir: /e2e
    depends_on:
      - ckan
    volumes:
    - ./e2e:/e2e
