version: '3'
services:
  app:
    build: .
    command: /opt/inventory-app/start.sh
    depends_on:
      - datastore
      - db
      - solr
    ports:
      - "5000:5000"
    env_file: env_file
    volumes:
      - ckan:/usr/lib/ckan
      - ./config:/etc/ckan
      - .:/opt/inventory-app

  datastore:
    image: postgres:9.6
    environment:
      POSTGRES_USER: datastore
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: datastore
    volumes:
      - ./datastore/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  datapusher:
    image: viderum/datapusher-1:v9
    ports:
      - "8800:8000"
    
  db:
    image: datagov/catalog-db:inventory2_8
    environment:
      POSTGRES_USER: postgres
      DB_CKAN_USER: ckan
      DB_CKAN_PASSWORD: pass
      DB_CKAN_DB: ckan

  solr:
    image: datagov/catalog-solr:inventory2_8

  redis:
    build: ./redis

  localstack-container:
    container_name: "localstack-container"
    privileged: true
    image: localstack/localstack:0.11.0
    ports:
      - "4566-4599:4566-4599"
      - "8081:8081"
    # https://github.com/localstack/localstack#configurations
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOSTNAME=
      - PORT_WEB_UI=8081
        # LAMBDA_EXECUTOR: Method to use for executing Lambda functions. Possible values are:
        #   local: run Lambda functions in a temporary directory on the local machine
        #   docker: run each function invocation in a separate Docker container
        #   docker-reuse: create one Docker container per function and reuse it across invocations
      - LAMBDA_EXECUTOR=docker-reuse
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
      - START_WEB=1
    volumes:
      - "./tmp/localstack:/tmp/localstack"
      - "./tmp/localstack/run/docker.sock:/var/run/docker.sock"
volumes:
  ckan:
