version: '3'
services:
  ckan:
    image: datagov/inventory-app:2.9
    build: .
    command: /app/start.sh
    depends_on:
      - datastore
      - db
      - solr
      - redis
      - localstack-container
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      CKAN_SITE_URL: http://localhost:5000
    volumes:
      - .:/app/
      #- ./ckanext-datagov_inventory:/usr/lib/ckan/src/ckanext-datagov_inventory
      # - /local/path/ckanext-some_extension/:/usr/lib/ckan/src/ckanext-some_extension

  datastore:
    image: postgres:9.6
    environment:
      POSTGRES_USER: datastore
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: datastore
    volumes:
      - ./datastore/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  db:
    image: datagov/catalog-db:inventory2_8
    environment:
      POSTGRES_USER: postgres
      DB_CKAN_USER: ckan
      DB_CKAN_PASSWORD: pass
      DB_CKAN_DB: ckan

  solr:
    image: ghcr.io/gsa/catalog.data.gov.solr:8-curl
    environment:
      - ZK_HOST=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
    # ports:
    #   - "8983:8983"
    deploy:
      replicas: 2
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  zookeeper1:
    image: zookeeper:3.7
    restart: always
    ports:
      - 2181:2181
    hostname: zookeeper1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - zookeeperdata:/data
      - zookeeperdatalog:/datalog

  zookeeper2:
    image: zookeeper:3.7
    restart: always
    ports:
      - 2182:2181
    hostname: zookeeper2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - zookeeperdata2:/data
      - zookeeperdatalog2:/datalog

  zookeeper3:
    image: zookeeper:3.7
    restart: always
    ports:
      - 2183:2181
    hostname: zookeeper3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    volumes:
      - zookeeperdata3:/data
      - zookeeperdatalog3:/datalog

  redis:
    image: redis:alpine

  localstack-container:
    container_name: "localstack-container"
    privileged: true
    image: localstack/localstack:0.11.0
    ports:
      - "4572:4572"
      - "8081:8081"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOSTNAME=
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
      - START_WEB=1
    volumes:
      - "./tmp/localstack:/tmp/localstack"
      - "./tmp/localstack/run/docker.sock:/var/run/docker.sock"
volumes:
  ckan:
  zookeeperdata:
  zookeeperdatalog:
  zookeeperdata2:
  zookeeperdatalog2:
  zookeeperdata3:
  zookeeperdatalog3:
