version: '3'
services:
  app:
    build: .
    env_file: env_file
    volumes:
      - ckan:/usr/lib/ckan
      - ./config:/etc/ckan
      - .:/opt/inventory-app
      - ../ckanext-s3filestore/:/usr/lib/ckan/src/ckanext-s3filestore/
      - ../ckanext-datajson/:/usr/lib/ckan/src/ckanext-datajson/