version: 2
jobs:
  lint:
    docker:
      - image: circleci/python:2.7.18
    steps:
      - run:
          name: lint code
          command: |
            pip install pip==20.3.3
            pip install flake8
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Run tests
          command: make test
      - run:
          name: Run extension tests
          command: |
            docker-compose run --rm app nosetests --ckan --with-pylons=docker_test.ini ckanext-datagov_inventory/ckanext/datagov_inventory/tests/*

  deploy-sandbox:
    docker:
      - image: circleci/python:3.6
    environment:
      JENKINS_URL: https://ci.sandbox.datagov.us
    steps:
      - checkout
      - deploy:
          name: jenkins
          command: bin/jenkins_build deploy-ci-app-inventory-next


workflows:
  version: 2
  commit:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - deploy-sandbox:
          requires:
            - lint
            - build
          filters:
            branches:
              only: inventory_ckan_2.8
