---
name: commit

on:
  push:


jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      REQUIREMENTS_FILE: requirements-freeze.txt
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: make test

  vendor:
    name: vendor dependencies
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: vendor dependencies
        run: ./vendor-requirements.sh
      - uses: actions/upload-artifact@v2
        with:
          name: python-vendored
          path: vendor/
          if-no-files-found: error

  deploy-development:
    if: github.ref == 'refs/heads/develop'
    name: deploy
    environment: development
    runs-on: ubuntu-latest
    needs:
      - test
      - vendor
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: python-vendored
          path: vendor
      - name: deploy
        uses: usds/cloud-gov-cli@master
        with:
          command: push ${{ secrets.CF_APP_NAME }} --vars-file vars.development.yml --strategy rolling
          org: ${{secrets.CF_ORG}}
          space: ${{secrets.CF_SPACE}}
          user: ${{secrets.CF_SERVICE_USER}}
          password: ${{secrets.CF_SERVICE_AUTH}}
