---
name: commit

on:
  push:


jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x']
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: lint
        run: |
          # TODO add this to dev dependencies and Makefile
          pip install --upgrade pip
          pip install flake8
          flake8 . --count --show-source --statistics

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: test
        run: make build test
      - name: test extension
        run: make test-extension
      - name: cypress-artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-artifacts
          path: |
            ./e2e/cypress/screenshots/
            ./e2e/cypress/videos/
