---
name: restart application

on:
  workflow_dispatch:
  schedule:
    - cron: '7/15 * * * *'  # every 15 mins

jobs:
  restart-staging:
    name: restart (staging)
    uses: gsa/data.gov/.github/workflows/app-restart-template.yml
    with:
      environ: staging
      app_names: "{\"include\":[{\"app\":\"inventory\"},{\"app\":\"inventory-proxy\"},]}"
    secrets: inherit

  restart-prod:
    name: restart (staging)
    uses: gsa/data.gov/.github/workflows/app-restart-template.yml
    with:
      environ: staging
      app_names: "{\"include\":[{\"app\":\"inventory\"},{\"app\":\"inventory-proxy\"},]}"
    secrets: inherit
