---
name: Check for Snyk Vulnerabilities

on:   # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # every day at 12pm UTC

jobs:
  snyk:
    name: snyk test
    runs-on: ubuntu-20.04   # Pin to have access to Python 3.8
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          npm install snyk -g
          sudo apt-get update -y
          sudo apt-get install -y \
            openssl libssl-dev libffi-dev pkg-config libxml2-dev \
            libxmlsec1-dev libxmlsec1-openssl libgeos-dev proj-bin
          pip3 install -r requirements.txt
      # yamllint disable rule:line-length
      - name: Run Snyk Scan
        run: |
          # Run scan
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --file=requirements.txt --json-file-output=scan.json || echo "Scan complete"

          # Exit if no vulnerabilities
          # Succeed, so that PR is NOT created
          [[ "$(jq '.ok' scan.json)" == "true" ]] && exit 0

          # Update requirements.in with the snyk fix suggestions
          python bin/snyk-update.py

          # Remove unnecessary file so that it doesn't get added to the repo
          rm scan.json

          # Update requirements.txt
          make requirements

          # Fail so that PR is created
          exit 1
      - name: Create Pull Request
        if: ${{ failure() }}
        id: scpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          commit-message: Update Pip Requirements
          committer: Data.gov Github <datagovhelp@gsa.gov>
          author: ${{ github.actor }} <datagovhelp@gsa.gov>
          signoff: false
          branch: requirement-patches
          delete-branch: true
          title: '[Snyk + GH Actions] Update requirements'
          body: |
            Update requirements
            - Updated `requirements.in` + `requirements.txt`
            - Auto-generated by [snyk.yml][1]

            [1]: https://github.com/gsa/inventory-app/.github/workflows/snyk.yml
          labels: |
            requirements
            automated pr
            snyk
          team-reviewers: data-gov-team
          draft: false
          # yamllint enable rule:line-length
